### ISSUE TITLE
we have a problem with VirtualScroller 

### ISSUE THREAD

**Issue by getmonyinfo** [primefaces/primevue#1485]
the VirtualScroller codesandbox example has errors, please fix

**Comment by mertsincan** [comment]
Thanks a lot! Fixed now.

Best Regards,

**Comment by getmonyinfo** [comment]
actually, the code still not  working!

[codesandbox](https://codesandbox.io/s/8mfuq)

**Comment by mertsincan** [comment]
Hi,

Please click demo link  again at https://primefaces.org/primevue/showcase/#/virtualscroller. Codesandbox demos are created dynamically.

Best Regards,
