### ISSUE TITLE
v-styleclass hideOnOutsideClick not working

### ISSUE THREAD

**Issue by vargen2** [primefaces/primevue#2483]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

When using primeblocks sidebar layout https://www.primefaces.org/primeblocks-vue/#/application/sidebarlayout

`v-styleclass="{
              selector: '#app-sidebar-1',
              enterClass: 'hidden',
              enterActiveClass: 'fadeinleft',
              leaveToClass: 'hidden',
              leaveActiveClass: 'fadeoutleft',
              hideOnOutsideClick: true
            }"`

**Current behavior**
Can't close sidebar when clicking outside (mobile mode) in version 3.12.4 and 3.12.5

**Expected behavior**
Can close sidebar when clicking outside (mobile mode)  in version 3.12.3

**Comment by tugcekucukoglu** [comment]
3.12.4 has a defect on styleclass directive. It has fixed 3.12.5. But I could not replicate the issue. Which block is working incorrectly?

**Comment by vargen2** [comment]
I think it is because I changed from absolute to fixed in <div id="app-sidebar-1"....

`old
 styleclass.js, line 140
if (isVisible(target) || getComputedStyle(target).getPropertyValue('position') === 'static')
{
                unbindDocumentListener(target);
            }`
            
           new 
           `if (!isVisible(target) || getComputedStyle(target).getPropertyValue('position') === 'static') {
                unbindDocumentListener(target);
            }`

**Comment by tugcekucukoglu** [comment]
Please use v3.12.5. If problem is still persist please reopen this ticket.

**Comment by wiz-kakiuchi** [comment]
same problem in 3.17.0

**Comment by kehwar** [comment]
i'm also experiencing this problem on 3.17.0

**Comment by rortlam** [comment]
Same here; if it helps: we only experience this issues in Chrome, while everything works perfectly fine in Firefox (current versions).

**Comment by TuroczyX** [comment]
I have the same issue in Angular as well with the latest versions.
"primeflex": "^3.2.1",
"primeng": "^14.2.1", 

hideOnOutsideClick simply does not work

**Comment by mikecbone** [comment]
Still an issue, same issue PrimeReact had too https://github.com/primefaces/primereact/issues/3080

@tugcekucukoglu Please reopen
