### ISSUE TITLE
DataTable: row group header colspan doesn't span full row when table has selection column

### ISSUE THREAD

**Issue by iampeternguyen** [primefaces/primevue#3685]
### Describe the bug

When using selection column and row group headers, the colspan for the row group header doesn't count the select column so it doesn't span the full row. 

![image](https://user-images.githubusercontent.com/27402378/221615256-f6bf40d4-64a4-41e0-bdc6-118091a3696c.png)

### Reproducer

https://codesandbox.io/s/modest-hamilton-q4v4nl

### PrimeVue version

2.10.1

### Vue version

2.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

See code sandbox and inspect row group header. colspan is 3 when it should be 4.

### Expected behavior

colspan for group headers should also include the selection column to span the full row.

**Comment by may820806** [comment]
same in 3.12.2.

**Comment by csmaller** [comment]
any fix for this? having the same problem

**Comment by csmaller** [comment]
Thank you,  I had to do a similar workaround almost the same code and yours seems a bit more elegant.  I need to make an async call to get the data first so a timeout didn't work...and a I have three tables with multiple selections  and different column count so It needs to get each colspan then add 1 to each, plus it is in Vue3.  

For anyone using Vue3 using TS I will post what I did here:

`const addColspanToHeader = () => {

  const groupHeaders = document.querySelectorAll("table tbody .p-rowgroup-header td")
  
  for (let item of groupHeaders) {
      const newColspan = parseInt(item.colSpan) + 1;
      item.colSpan = newColspan;
  }
};`

**Comment by alansgonzaga** [comment]
Same probleme here, I used @csmaller code, and it worked for when I load the table, but when I make a sort or a filter, it goes back to the problem. My workaround was to get the emits for sort, filtering, rowschange... I got all of them, and made them all call the function addColspanToHeader() with a timeout to execute... Worked, but kind of messy...

![image](https://github.com/primefaces/primevue/assets/26310779/fba0f97e-3b4f-44b5-8cef-696acafa2a6b)

Problem:
![image](https://github.com/primefaces/primevue/assets/26310779/cb0ee0be-5a1f-4284-9890-2681952ba353)

With workaround:
![image](https://github.com/primefaces/primevue/assets/26310779/fe28c161-edda-41ee-bc0e-00308ef463b4)

**Comment by csmaller** [comment]
3.34.1 still not working.  steps: updated primevue in package.json to 3.34.1 cleared cache and opened in Incognito.  Still broken

**Comment by csmaller** [comment]
I included one of the data tables that is causing this problem.  Could be a few variables that are causing this. maybe you can see the problem better than I...  thanks

` <DataTable
          v-model:selection="invoicesToGenerateSelected"
          v-model:filters="filters"
          filter-display="menu"
          :value="invoicesReadyToGenerate"
          :total-records="invoicesReadyToGenerate?.length || 0"
          data-key="id"
          row-group-mode="subheader"
          group-rows-by="organization_id"
          :lazy="true"
          loading-icon="logo-spinner"
          :loading="billingStore.loading"
          responsive-layout="scroll"
          class="text-sm"
        >
          <Column selection-mode="multiple" header-style="width: 4em">
            <template #body="{ data }">
              <Checkbox v-else v-model="invoicesToGenerateSelected" :value="data" :disabled="isGeneratingInvoices" />
            </template>
          </Column>
          <Column field="invoice_number" header="Invoice #">
            <template #body="{ data }">
              <span
                class="text-primary font-semibold cursor-pointer"
                @click="openBillingModal(data.id)"
                v-text="data.invoice_number"
              />
            </template>
          </Column>
          <Column field="dates" header="Dates">
            <template #body="{ data }">
              {{ dateUtilities.formatIntlDate(data.start_at) }} - {{ dateUtilities.formatIntlDate(data.end_at) }}
            </template>
          </Column>
          <Column field="send_on" header="Send On">
            <template #body="{ data }">
              {{ dateUtilities.formatIntlDate(data.send_on) }}
            </template>
          </Column>
          <Column field="totals" header="Invoice Totals">
            <template #body="{ data }">
              {{ useCurrency().formatCurrency(data.total) }}
            </template>
          </Column>
          <template #groupheader="{ data }">
            <div class="flex gap-2 align-items-center bg-primary-100">
              <span class="mr-2 text-gray-600 font-semibold text-sm">{{ data.organization.name }}</span>
              <Icon
                v-if="data.organization.location"
                v-tooltip.bottom="{
                  value: subTag(data.organization.location),
                  escape: true,
                  fitContent: true,
                }"
                name="info"
                class="text-primary-500 text-base cursor-pointer"
              />
              <span v-if="data.third_party" class="third-party font-bold">3rd Party</span>
              <span v-if="data.prepay" class="prepay font-bold">Prepay</span>
            </div>
          </template>
        </DataTable>`

**Comment by kkurys** [comment]
@csmaller Please  try adding another column:
```
          <Column field="organization_id" header="">
          </Column>
```
This won't render anyways, but will resolve the issue of the subheader spanning wrong number of columns (I think :D)

**Comment by deyanaaliyah** [comment]
I know the issue is closed but [kkurys](https://github.com/kkurys) made a nice suggestion.

 I'm using 
- vue ```3.2.x```
- primevue ```3.49.x```

I added an extra empty column and **it helped**.

```vue
<template>
        <DataTable rowGroupMode="subheader">
                <Column field="field1" header="field1"></Column>
                <Column field="field1" header="field1"></Column>
                <Column field="field2" header="field2"></Column>
                <Column field="field3" header="field3"></Column>
                <Column field="field4" header="field4"></Column>
                <Column field="field5" header="field5"></Column>

               <!-- Added this -->
               <Column field="" header="" style="display: none;"></Column>

                <template #groupheader="slotProps"></template>
                <template #groupfooter="slotProps"></template>
        </DataTable>
</template>
```

**Comment by philipimperato** [comment]
Was this fixed in 4.1? I can't seem to make this work.

**Comment by majoess** [comment]
@philipimperato still not fixed but @deyanaaliyah answer https://github.com/primefaces/primevue/issues/3685#issuecomment-2107187144 works for now great.

**Comment by jacobg** [comment]
The following DataTable attribute fixes it for me:
```
:pt="{ rowGroupHeaderCell: { colspan: 3 }}"
```
https://primevue.org/datatable/#api.datatable.interfaces.DataTablePassThroughOptions.rowGroupHeaderCell

**Comment by Rillion124** [comment]
it works
<Column class="col-off"></Column>
.col-off{
    display: none;
}

**Comment by james-onpoint** [comment]
This needs to be fixed natively in PrimeVue

**Comment by HannesJoerk0174** [comment]
> :pt="{ rowGroupHeaderCell: { colspan: 3 }}"

This fix worked perfectly!
Also it appears that the expander row for expansions is not being counted either.

**Comment by mergehez** [comment]
The problem is still not solved after 3 years..
