### ISSUE TITLE
MultiSelect: selectionMessage not changing using locales

### ISSUE THREAD

**Issue by itpzzi** [primefaces/primevue#3929]
### Describe the bug

According to the documentation, it is described that it is possible to change the messages, including the one for the number of selected items. However, applying the translation for the "selectionMessage" does not have any effect, even using different translation files. I needed to use the Portuguese version "{0} itens selecionados", but the component continues to display "{0} items selected" no matter what I do.

![image](https://user-images.githubusercontent.com/88782509/236539420-1a9e40c7-9f5d-4624-b764-7903dabbef72.png)

Looking at the code, I suspect that it is the computed variable that is used in the template, not taking into account the translation definitions.
![image](https://user-images.githubusercontent.com/88782509/236538714-4fa8d717-99ba-4c89-8d63-8f3cdf3c2cef.png)

### Reproducer

https://codesandbox.io/s/laughing-snowflake-j73vgg

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

any

### Steps to reproduce the behavior

1. Define a translation file with any language other than English and set it in VuePrime config options;
2. Use a MultiSelect component;
3. Select multiple items;
4. When the maximum number of items defined in maxSelectedLabels is reached, note that the quantity label is in English.

### Expected behavior

I needed to use the Portuguese version "{0} itens selecionados"

**Comment by victormedeiros1** [comment]
Same for me, was resolved?

**Comment by tugcekucukoglu** [comment]
The issue is fixed for the next version. Please track  at https://github.com/primefaces/primevue/issues/4558

**Comment by lucasdevdotnet** [comment]
esse problema já foi solocionado sabem informar ?

**Comment by UnforgetMemory** [comment]
Unfortunately, in the latest version @ 4.0.5, this issue still exists. The locle of other components is normal.

**Comment by losthunter52** [comment]
Use the selectedItemsLabel prop

<MultiSelect selectedItemsLabel="{0} Columns Selected" ...
