### ISSUE TITLE
Calendar: Timepicker changes from `12 am` to `12 pm` automatically

### ISSUE THREAD

**Issue by zernonia** [primefaces/primevue#4449]
### Describe the bug

The timepicker in calendar changes from manual input `12:30 am` to `12:30 pm` when lose focus.

### Reproducer

https://codesandbox.io/p/sandbox/quizzical-hooks-xlmrqd?welcome=true

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

(important: having props = hour-format="12",  time-only)

1. Open the repro link
2. Manually change the `input` to `12: 30 am`, click outside from the input
3. Observe the `am` changed to `pm`
 

https://github.com/primefaces/primevue/assets/59365435/067e95ac-73ba-4baa-b224-a78627888ce6

### Expected behavior

It should remain `12: 30 am`.

**Comment by zernonia** [comment]
PR is ready 😁
https://github.com/primefaces/primevue/pull/4451

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/4451

**Comment by dmhendricks** [comment]
@mertsincan - I'm trying to figure out if I'm crazy or if this bug still exists in 3.36.0. I can reproduce it on the [documentation page](https://primevue.org/calendar/) demo...

To reproduce it:
1. Go here: https://primevue.org/calendar/
2. Select a date and time. Make the time 12:xx am. Example:
<img width="396" alt="Screenshot 2023-10-11 at 10 56 36 AM" src="https://github.com/primefaces/primevue/assets/8184361/32e4478e-6098-4a20-8229-35502d172848">

3. Click off of field to remove focus (you can click anywhere else on the page)
4. Click on the field again and select any **date**. When you do that, the "am" will automatically change to "pm" even though the time wasn't changed/touched:
<img width="392" alt="Screenshot 2023-10-11 at 10 58 51 AM" src="https://github.com/primefaces/primevue/assets/8184361/089b8eae-e7ef-4157-befe-a23b0272dc5e">

**Comment by dmhendricks** [comment]
This is still happening in 3.46.0, including on the documentation page.
