### ISSUE TITLE
`zIndex` not taken into account e.g. between Menubar and Sidebar

### ISSUE THREAD

**Issue by tmlmt** [primefaces/primevue#4552]
### Describe the bug

Menu dropdowns stay below Sidebar despite setting [`zIndex`](https://primevue.org/configuration/#zindex) to have menus or overlays above modals (not sure which category menu dropdowns belong to)

```
app.use(PrimeVue, {
  ripple: true,
  zIndex: {
    modal: 1100, //dialog, sidebar
    overlay: 1200, //dropdown, overlaypanel
    menu: 1200, //overlay menus
    tooltip: 1100, //tooltip
  },
});
```

![image](https://github.com/primefaces/primevue/assets/10244927/41fdc445-45b5-4582-82c7-63a3993d2389)

### Reproducer

https://codesandbox.io/p/sandbox/goofy-shamir-tmm3nv

### PrimeVue version

3.35.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Tested on Chromium 116.0.5845.96 and Firefox 118.0.1

### Steps to reproduce the behavior

In the reproducer:
1. Click on "Open Sidebar"
2. Click on the Menu to open the dropdown

### Expected behavior

The Menu dropdown should be above the Sidebar

**Comment by SelenKockar** [comment]
Hi @tmlmt
 I think, the issue is fixed for new version 3.36.0. There was no error in my local.
Let me know if you get the same error.

**Comment by tmlmt** [comment]
Hey @SelenKockar, in the Code Sandbox indeed the issue seems fixed. I will check this on my own project later this week. 

I couldn't find which commit fixed this though. Do you have an idea?

**Comment by tmlmt** [comment]
Hey @SelenKockar, I checked on the Code Sandbox Reproducer: the issue is still there.

If you're referring to your merged PR, I can see you only corrected the dock section of the documentation, not Primevue itself?

**Comment by SelenKockar** [comment]
Hi @tmlmt ,

I wasn't talking about my own PR. The current issue in my locale seems to be resolved if you are working with Vite. I will check it again.
Kind regards

**Comment by tugcekucukoglu** [comment]
Firstly, thanks for the demo link. I ran the demo but can not replicate the issue. How can I see the problem?

![Screenshot 2023-10-17 at 17 08 32](https://github.com/primefaces/primevue/assets/32294991/fae242b6-4a50-4ef6-87cf-8159970f408e)

**Comment by tmlmt** [comment]
Hey @tugcekucukoglu, very strange stuff ! I've just tried two different laptops just now:
- Laptop 1 on Windows 10 and Chrome 118.0.5993.71
  - Same screenshot as the one you posted where there's no issue 😮
- Laptop 2 on Ubuntu 22.04.3 and ungoogled-chromium 118.0.5993.70
  - Issue confirmed ✅
Couldn't think of why ...

So I went back to Laptop 1, and could confirm again the issue when popping out the app in a new tab by clicking on this button :
<img width="559" alt="image" src="https://github.com/primefaces/primevue/assets/10244927/e1b2d094-58a5-48e7-82be-7b468502188f">
which I guess is the way it's supposed to look like in reality, when not in a iframe in that sandbox environment.
And was then able to see the issue: 
<img width="421" alt="image" src="https://github.com/primefaces/primevue/assets/10244927/e980516c-12e4-4a79-b154-c707d981520f">

When it's in the iframe on Laptop 1 (no issue) as you could see yourself, I could notice that the menu dropdown (a `<ul>` with class `p-menubar-root-list`) is styled with a `z-index` above 2000 so above that of the Sidebar (1101). 
<img width="933" alt="image" src="https://github.com/primefaces/primevue/assets/10244927/6b9fd96e-3e3d-44ce-b3a0-873ffa9e416d">
However when the app is loaded from a separate tab on Laptop 1 or in any situation on Laptop 2, the same `<ul>` does not get a z-index, there's no style attribute.

Could you try yourself and confirm?

**Comment by tugcekucukoglu** [comment]
I think I need to test this in a completely codesandbox-free environment. I will create a repo for that, but I want to say that I don't have an Ubuntu test environment right now.

**Comment by tmlmt** [comment]
The issue is found on both environments once you open the website on a separate tab. 

I don't have a non-Linux test environment myself. Can you simply try downloading the sandbox project to run it locally on your machine and see if the issue's indeed reproducible?

**Comment by tugcekucukoglu** [comment]
I'm sorry for not getting back to you sooner.

Menubar has huge changes with the latest version. If the problem persists, we can reopen this issue. Closing for now.
