### ISSUE TITLE
Editor: `v-model` not updating with Quill v2.0

### ISSUE THREAD

**Issue by FeBe95** [primefaces/primevue#5606]
### Describe the bug

Quill v2.0 is now officially released (see https://github.com/quilljs/quill/releases). PrimeVue's docs state to simply run
```
npm install quill
```
to make the Editor component work. Displaying and editing the text inside the editor works just fine, but directly manipulating the `v-model` value does not. This issue was mentioned here as well:
- #5381 

I know that there are plans to replace Quill with a custom solution (mentioned in a discussion [here](https://github.com/orgs/primefaces/discussions/697#discussioncomment-7908565)), but until then a fix for this issue would be very appreciated.

### Reproducer

https://stackblitz.com/edit/primevue-create-vue-issue-template-fsd4z9

### PrimeVue version

3.51.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Use the Editor component
2. Set/update the `v-model` value

### Expected behavior

The content of the Editor should change. It does not.

**Comment by jeverduzco** [comment]
> Same thing here. The editor works to write new texts. To edit something is not working

Same issue.

**Comment by kristuu** [comment]
Same issue here and I couldn't figure out anything I could do even for a temporary fix.

**Comment by arikardnoir** [comment]
The same for me here, everyone that can help us, please give us some lights.

**Comment by pedrodruviaro** [comment]
> In the meantime you can install quill 1.3.7. that's the latest non-2.0 version.
> 
> I just came to visit after seeing this in my console:
> 
> ```
> # npm audit report
> 
> quill  <=1.3.7
> Severity: moderate
> Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
> fix available via `npm audit fix --force`
> Will install quill@2.0.0, which is a breaking change
> ```

That worked. However, we have the performance problem mentioned here: https://github.com/vueup/vue-quill/issues/409
But I think this is the best solution until this v-model problem is not resolved

**Comment by agm1984** [comment]
> That worked. However, we have the performance problem mentioned here: [vueup/vue-quill#409](https://github.com/vueup/vue-quill/issues/409) But I think this is the best solution until this v-model problem is not resolved

Thanks, I did notice that in my project but I didn't debug it yet, so thats good to know.

**Comment by arikardnoir** [comment]
> > In the meantime you can install quill 1.3.7. that's the latest non-2.0 version.
> > I just came to visit after seeing this in my console:
> > ```
> > # npm audit report
> > 
> > quill  <=1.3.7
> > Severity: moderate
> > Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
> > fix available via `npm audit fix --force`
> > Will install quill@2.0.0, which is a breaking change
> > ```
> 
> That worked. However, we have the performance problem mentioned here: [vueup/vue-quill#409](https://github.com/vueup/vue-quill/issues/409) But I think this is the best solution until this v-model problem is not resolved

What you guys did? i cant understand, im already using quill 2.0.0, and still not working the getting the value

**Comment by agm1984** [comment]
> What you guys did? i cant understand, im already using quill 2.0.0, and still not working the getting the value

I left quill at version 1.3.7 until v2 is supported.

```
$ npm uninstall --save quill
$ npm install --save quill@^1.3.7
```

**Comment by arikardnoir** [comment]
> > What you guys did? i cant understand, im already using quill 2.0.0, and still not working the getting the value
> 
> I left quill at version 1.3.7 until v2 is supported.
> 
> ```
> $ npm uninstall --save quill
> $ npm install --save quill@^1.3.7
> ```

Many thanks @agm1984, it works for me

**Comment by FeBe95** [comment]
For reference: This is the corresponding issue (and PR) from [primefaces/primereact](https://github.com/primefaces/primereact) repository. A fix for PrimeVue could be almost copy & paste, I guess:
- https://github.com/primefaces/primereact/issues/5960
- https://github.com/primefaces/primereact/pull/6429

**Comment by LeonardoRochaInacio** [comment]
Probably the best solution for this issue is: 

**First, set a ref for the editor component and bind a method for the load event emitted by the component** 
```javascript
<Editor ref="editor" v-model="form.description" @load="editorLoad">
```

**So, after that, create a method for being executed after editor load:** 
```javascript
editorLoad({instance}) {
    const delta = this.$refs.editor.quill.clipboard.convert({ html: "<p>your html goes here!</p>" });
    this.$refs.editor.quill.setContents(delta, 'silent');
},
```

**Comment by visgotti** [comment]
> Probably the best solution for this issue while using quill >= 2.0.0 is:
> 
> **First, set a ref for the editor component and bind a method for the load event emitted by the component**
> 
> ```js
> <Editor ref="editor" v-model="form.description" @load="editorLoad">
> ```
> 
> **So, after that, create a method for being executed after editor load:**
> 
> ```js
> editorLoad({instance}) {
>     const delta = this.$refs.editor.quill.clipboard.convert({ html: "<p>your html goes here!</p>" });
>     this.$refs.editor.quill.setContents(delta, 'silent');
> },
> ```

this worked but also had to call my `editorLoad` function inside a watch callback, also needed to use nextTick to get this working properly. 

``` js
const editorLoad = () => {
  const newValue = isEditing.value || isCreating.value
      ? editingValue.value
      : selectedValue.value;
  const delta = editor.value.quill.clipboard.convert({
    html: newValue || ""
  });
  nextTick(() => editor.value.quill.setContents(delta));
};
watch([selectedValue, isEditing, isCreating], editorLoad);
```

**Comment by BeinRain06** [comment]
> Using script setup
> 
> ```js
> const editorRef = ref()
> 
> watch(editorRef, (editor) => {
>   if (!editor) return
>   // Hack needed for Quill v2: https://github.com/primefaces/primevue/issues/5606#issuecomment-2093536386
>   editor.renderValue = function renderValue(value) {
>     if (this.quill) {
>       if (value) {
>         const delta = this.quill.clipboard.convert({ html: value })
>         this.quill.setContents(delta, 'silent')
>       } else {
>         this.quill.setText('')
>       }
>     }
>   }.bind(editor) // Bind needed for production build
> })
> ```
> 
> ```
> <Editor ref="editorRef" />
> ```

worked for me , using script setup . I just replace **value** with **postItem.value.content**, where postItem is also a ref 

taking a new value when the component is **mounted** :

    `let postItem = ref({
  id: '',
  title: '',
  image: '',
  summary: '',
  content: '',
  author: ''
})

onMounted(() => {
  const postStore = usePostStore()
  const postToEdit = postStore.postInPage

  postItem.value.id = postToEdit._doc.id
  postItem.value.title = postToEdit._doc.title
  postItem.value.image = postToEdit._doc.image
  postItem.value.summary = postToEdit._doc.summary
  postItem.value.content = postToEdit._doc.content
  postItem.value.author = postToEdit._doc.author
})`

and then writing:

    `watch(editorRef, (editor) => {
  if (!editor) return
  // Hack needed for Quill v2: https://github.com/primefaces/primevue/issues/5606#issuecomment-2093536386
  editor.renderValue = function renderValue(value) {
    if (this.quill) {
      console.log('yeah')
      if (postItem.value.content) {
        console.log('yeah yeah')
        const delta = this.quill.clipboard.convert({ html: postItem.value.content })
        this.quill.setContents(delta, 'silent')
      } else {
        console.log('no no')
        this.quill.setText('')
      }
    }
  }.bind(editor) // Bind needed for production build
})`

**Comment by iwind** [comment]
> > Using script setup
> > ```js
> > watch(editorRef, (editor) => {
> >   if (!editor) return
> >   // Hack needed for Quill v2: https://github.com/primefaces/primevue/issues/5606#issuecomment-2093536386
> >   editor.renderValue = function renderValue(value) {
> >     if (this.quill) {
> >       if (value) {
> >         const delta = this.quill.clipboard.convert({ html: value })
> >         this.quill.setContents(delta, 'silent')
> >       } else {
> >         this.quill.setText('')
> >       }
> >     }
> >   }.bind(editor) // Bind needed for production build
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > <Editor ref="editorRef" />
> > ```
> 
> worked for me , using script setup . I just replace **value** with **postItem.value.content**, where postItem is also a ref
> 
> taking a new value when the component is **mounted** :
> 
> > ```js
> > <script setup>
> >  // pinia store
> >  import { usePostStore } from '@/stores/post' 
> > 
> >  let postItem = ref({
> >    id: '',
> >    title: '',
> >    content: '',
> >  })
> > 
> > onMounted(() => {
> >  const postStore = usePostStore()
> >  const postToEdit = postStore.postInPage
> > 
> >  postItem.value.id = postToEdit._doc.id
> >  postItem.value.title = postToEdit._doc.title
> >  postItem.value.content = postToEdit._doc.content
> > })
> > 
> > watch(editorRef, (editor) => {
> >  if (!editor) return
> >    editor.renderValue = function renderValue(value) {
> >      if (this.quill) {
> >        if (postItem.value.content) {
> >          const delta = this.quill.clipboard.convert({ html: postItem.value.content })
> >          this.quill.setContents(delta, 'silent')
> >        } else {
> >          this.quill.setText('')
> >       }
> >   }
> >  }.bind(editor) // Bind needed for production build
> > })
> > </script>
> > ```

my improvement based the code:

~~~
const props = defineProps(["modelValue"])

function initEditorValue({instance}) {
	instance.setContents(instance.clipboard.convert({
		html: props.modelValue
	}));
}

</script>

<template>
	<Editor @load="initEditorValue"></Editor>
</template>
~~~

**Comment by iwind** [comment]
You can define a new customized component 'MyEditor': 

~~~vue
<script setup>
import Editor from "primevue/editor"

const props = defineProps({
	modelValue: {
		type: String,
		default: ""
	}
})

const emits = defineEmits(["update:modelValue"])

const onLoad = ({instance}) => {
	instance.setContents(instance.clipboard.convert({
		html: props.modelValue
	}))
}

const onChange = (v) => {
	emits("update:modelValue", v)
}
</script>

<template>
	<Editor editorStyle="height: 20em" @load="onLoad" @update:modelValue="onChange"></template>
	</Editor>
</template>
~~~

works well with  `"quill": "^2.0.2"`

**Comment by tfoxkiu** [comment]
Based on my previous answer, an easier way is to patch `renderValue` in the component definition.

```js
import Editor from 'primevue/editor';

Editor.methods.renderValue = function renderValue(value) {
  if (this.quill) {
    if (value) {
      const delta = this.quill.clipboard.convert({ html: value });
      this.quill.setContents(delta, 'silent');
    } else {
      this.quill.setText('');
    }
  }
};
```

In TypeScript:

```ts
import Editor from 'primevue/editor';

(Editor as any).methods.renderValue = function renderValue(value: string) {
  if (this.quill) {
    if (value) {
      const delta = this.quill.clipboard.convert({ html: value });
      this.quill.setContents(delta, 'silent');
    } else {
      this.quill.setText('');
    }
  }
};
```

This needs to be executed only once and it will apply to every instance of `Editor`. So you can just use `<Editor />` and it will work. This has the following advantages:

- There's no need to apply the fix every time you want to use `Editor`.
- There's no need to create a wrapper, which would lose the autocompletion/typing and it's harder to implement if you want all the props and events of `Editor`.

**Comment by reqwire** [comment]
If you want to use 2.0.2 with <script setup>, TypeScript and be able to use all props:

`<template>
  <Editor v-bind="props" @load="onLoad" @update:modelValue="onChange" />
</template>

<script setup lang="ts">
import Editor, { type EditorLoadEvent, type EditorProps } from 'primevue/editor';

const props = defineProps<EditorProps>();

const emits = defineEmits(['update:modelValue']);

const onLoad = ({ instance }: EditorLoadEvent) => {
  instance.setContents(
    instance.clipboard.convert({
      html: props.modelValue
    })
  );
};

const onChange = (v: string) => {
  emits('update:modelValue', v);
};
</script>
`

**Comment by reqwire** [comment]
If you want to be able to use Quill 2.0+ with **<script setup>**, **TypeScript** and have access to **all props**:

```
<template>
  <Editor v-bind="props" @load="onLoad" @update:modelValue="onChange" />
</template>

<script setup lang="ts">
import Editor, { type EditorLoadEvent, type EditorProps } from 'primevue/editor';

const props = defineProps<EditorProps>();

const emits = defineEmits(['update:modelValue']);

const onLoad = ({ instance }: EditorLoadEvent) => {
  instance.setContents(
    instance.clipboard.convert({
      html: props.modelValue
    })
  );
};

const onChange = (v: string) => {
  emits('update:modelValue', v);
};
</script>
```

**Comment by Hudhaifa-1** [comment]
> > What you guys did? i cant understand, im already using quill 2.0.0, and still not working the getting the value
> 
> I left quill at version 1.3.7 until v2 is supported.
> 
> ```
> $ npm uninstall --save quill
> $ npm install --save quill@^1.3.7
> ```

@agm1984 Thank you so much bro, it works for me

**Comment by francois-launchbase** [comment]
This Chrome [deprecation](https://developer.chrome.com/blog/mutation-events-deprecation) has taken effect two days ago (23rd July)  and since then I've started seeing this error on any pages with the editor component:
`[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired.`

This is visible in the console logs of the official [site](https://primevue.org/editor/) as well.

It looks like this is caused by quill v1 :fearful: (I'm not sure if quill v2 resolves this).

**Comment by matlimaaa** [comment]
> You can define a new customized component 'MyEditor':
> 
> ```
> <script setup>
> import Editor from "primevue/editor"
> 
> const props = defineProps({
> 	modelValue: {
> 		type: String,
> 		default: ""
> 	}
> })
> 
> const emits = defineEmits(["update:modelValue"])
> 
> const onLoad = ({instance}) => {
> 	instance.setContents(instance.clipboard.convert({
> 		html: props.modelValue
> 	}))
> }
> 
> const onChange = (v) => {
> 	emits("update:modelValue", v)
> }
> </script>
> 
> <template>
> 	<Editor editorStyle="height: 20em" @load="onLoad" @update:modelValue="onChange"></template>
> 	</Editor>
> </template>
> ```
> 
> works well with `"quill": "^2.0.2"`


Funcionou certinho!! Obrigadoo

Tive um pequeno desafio pois meu componente não inicializava com o conteúdo, a menos que eu modificasse o arquivo dele e ai então ele carregava o conteúdo. Acrescentei o seguinte código para garantir:

```
<template>
        <Editor ref="editorRef" editorStyle="height: 250px" @load="onLoad" @update:modelValue="onChange"></Editor>
</template>

<script setup>
const updateEditorContent = (content) => {
	if (editorRef.value) {
		const editor = editorRef.value.quill;
		editor.setContents(editor.clipboard.convert({
			html: content
		}))
	}
}

watch(() => props.modelValue, (newValue) => {
	updateEditorContent(newValue)
}, { immediate: true })
</script>
```

**Comment by agm1984** [comment]
I just updated PrimeVue to v4 and got this issue when I bumped up Quill to v2.

This problem is still happening.

**Comment by douglas73** [comment]
> If you want to be able to use Quill 2.0+ with **<script setup>**, **TypeScript** and have access to **all props**:
> 
> **@/components/TextEditor.vue**
> 
> ```
> <template>
>   <Editor v-bind="props" @load="onLoad" @update:modelValue="onChange" />
> </template>
> 
> <script setup lang="ts">
> import Editor, { type EditorLoadEvent, type EditorProps } from 'primevue/editor';
> 
> const props = defineProps<EditorProps>();
> 
> const emits = defineEmits(['update:modelValue']);
> 
> const onLoad = ({ instance }: EditorLoadEvent) => {
>   instance.setContents(
>     instance.clipboard.convert({
>       html: props.modelValue
>     })
>   );
> };
> 
> const onChange = (v: string) => {
>   emits('update:modelValue', v);
> };
> </script>
> ```

Funcionou perfeitamente aqui, muito obrigado pela ajuda.

**Comment by kpatrick05** [comment]
`<script setup>
import { watch, ref } from "vue";
import Editor from "primevue/editor";

const props = defineProps({
    modelValue: {
        type: String,
        default: ""
    }
});

const emits = defineEmits(["update:modelValue"]);

let quillInstance = null; 
const isProgrammaticUpdate = ref(false); 

const onLoad = ({ instance }) => {
    quillInstance = instance; 
    instance.setContents(instance.clipboard.convert({ html: props.modelValue }));
};

const onChange = () => {
    if (!isProgrammaticUpdate.value) {
        const editorContent = quillInstance.root.innerHTML.trim();
        emits("update:modelValue", editorContent); 
    }
};

watch(() => props.modelValue, (newValue) => {
    if (quillInstance) {
        const currentContent = quillInstance.root.innerHTML.trim(); 
        if (newValue !== currentContent) {
            isProgrammaticUpdate.value = true;
            quillInstance.setContents(quillInstance.clipboard.convert({ html: newValue }));
            isProgrammaticUpdate.value = false;
        }
    }
});
</script>

<template>
    <Editor editorStyle="height: 20em" @load="onLoad" @input="onChange">
        <template v-slot:toolbar>
            <span class="ql-formats">
                <select class="ql-header">
                    <option value="1"></option>
                    <option value="2"></option>
                    <option selected></option>
                </select>
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-list" value="ordered"></button>
                <select class="ql-align"></select>
                <select class="ql-color"></select>
            </span>
        </template>
    </Editor>
</template>
`

with full focus if the modelvalue is updating

**Comment by MathieuB1** [comment]
Hi there,

For the ones who use vue3 or nuxt3 with primevue v3, this solution properly works during init and updates:

```
<template>
	<Editor ref="editorRef" :editorStyle="`height: ${size};`" @load="onLoad" @update:modelValue="onChange">
		<template v-slot:toolbar>
			<span class="ql-formats">

				<select class="ql-header">
					<option value="1"></option>
					<option value="2"></option>
					<option selected></option> <!-- Default normal text -->
				</select>
				<button class="ql-bold"></button>
				<button class="ql-italic"></button>
				<button class="ql-underline"></button>
				<button class="ql-strike"></button>

				<button class="ql-align"></button>
				<button class="ql-list" value="ordered"></button>
				<button class="ql-list" value="bullet"></button>

				<select class="ql-color"></select>
				<select class="ql-background"></select>

				<button class="ql-link"></button>
				<button class="ql-image"></button>

			</span>
		</template>
	</Editor>
</template>

<script setup>
const props = defineProps({
	modelValue: String,
	size: String
})

const emits = defineEmits(["update:modelValue"])

const editorRef = ref();


const textValue = ref();

const updateEditorContent = () => {
	if (editorRef.value && editorRef.value.quill) {
		const editor = editorRef.value.quill;
		const currentContent = editor.root.innerHTML; // Get the current HTML content
		// Update only if modelValue differs from editor's current content
		if (currentContent !== props.modelValue) {
			const delta = editor.clipboard.convert({ "html": props.modelValue}); // Convert the HTML to Quill Delta
			editor.setContents(delta);
		}
	}
}


// Handle editor content change
const onChange = (v) => {
	emits("update:modelValue", v)
}

watch(() => props.modelValue, () => {
	 updateEditorContent();
})


const onLoad = () => {
	updateEditorContent();
}
</script>

```

Will be nice to add it to primevue 3...

**Comment by stefdomandtom** [comment]
Hi there. When I install latest quill version then the bullet list option in toolbar adds ol tags instead of ul tags. In 1.3.7 version it works correctly. What is the workaround since the 1.3.7 is not safe to use. Thanks in advance

**Comment by hamzehparsi** [comment]
In Nuxt version 3.13.2 with Nitro 2.9.7, the Quill option version 2.0.2 does not work with v-model and cannot render the content editor inside itself.

**Comment by tan-wood** [comment]
> Hi there. When I install latest quill version then the bullet list option in toolbar adds ol tags instead of ul tags. In 1.3.7 version it works correctly. What is the workaround since the 1.3.7 is not safe to use. Thanks in advance

I've had this issue as well

**Comment by zahedur** [comment]
> Based on my previous answer, an easier way is to patch `renderValue` in the component definition.
> 
> ```js
> import Editor from 'primevue/editor';
> 
> // Fix needed for Quill v2: https://github.com/primefaces/primevue/issues/5606#issuecomment-2203975395
> Editor.methods.renderValue = function renderValue(value) {
>   if (this.quill) {
>     if (value) {
>       const delta = this.quill.clipboard.convert({ html: value });
>       this.quill.setContents(delta, 'silent');
>     } else {
>       this.quill.setText('');
>     }
>   }
> };
> ```
> 
> In TypeScript:
> 
> ```ts
> import Editor from 'primevue/editor';
> 
> // Fix needed for Quill v2: https://github.com/primefaces/primevue/issues/5606#issuecomment-2203975395
> ;(Editor as any).methods.renderValue = function renderValue(
>   this: { quill?: Quill },
>   value: string,
> ) {
>   if (this.quill) {
>     if (value) {
>       const delta = this.quill.clipboard.convert({ html: value })
>       this.quill.setContents(delta, 'silent')
>     } else {
>       this.quill.setText('')
>     }
>   }
> }
> ```
> 
> This needs to be executed only once and it will apply to every instance of `Editor`. So you can just use `<Editor />` and it will work. This has the following advantages:
> 
> * There's no need to apply the fix every time you want to use `Editor`.
> * There's no need to create a wrapper, which would lose the autocompletion/typing and it's harder to implement if you want all the props and events of `Editor`.

It's worked, thank you

**Comment by hamzehparsi** [comment]
> zahedur

Thank you very much, the problem is solved

**Comment by hamzehparsi** [comment]
“I wish they would solve this issue within the component itself so that this code wouldn’t be necessary.”

**Comment by devtopher** [comment]
> If you want to be able to use Quill 2.0+ with **<script setup>**, **TypeScript** and have access to **all props**:
> 
> **@/components/TextEditor.vue**
> 
> ```
> <template>
>   <Editor v-bind="props" @load="onLoad" @update:modelValue="onChange" />
> </template>
> 
> <script setup lang="ts">
> import Editor, { type EditorLoadEvent, type EditorProps } from 'primevue/editor';
> 
> const props = defineProps<EditorProps>();
> 
> const emits = defineEmits(['update:modelValue']);
> 
> const onLoad = ({ instance }: EditorLoadEvent) => {
>   instance.setContents(
>     instance.clipboard.convert({
>       html: props.modelValue
>     })
>   );
> };
> 
> const onChange = (v: string) => {
>   emits('update:modelValue', v);
> };
> </script>
> ```

This worked for me. Thank you

**Comment by devtopher** [comment]
If anyone else is having problems editing links with this, i.e you add a link, then go back and edit it, if Quill is clearing your text, it's because setContents is getting called and deleting the text even if your model value persists.

This is what we did to "fix" that.

 const onLoad = ({ instance }: EditorLoadEvent) => {
    instance.setContents(
      instance.clipboard.convert({
        html: props.modelValue
      })
    );
    instance.setContents = () => {
      // we replace this function with nothing so it stops breaking editing links
    };
  };

**Comment by FeBe95** [comment]
This is now fixed! 🎉

**PrimeVue 4.2.5 + Quill 2.0.3:**
https://stackblitz.com/edit/primevue-4-vite-issue-template-zqth8o5q?file=src%2FApp.vue

**Comment by FeBe95** [comment]
Unfortunately there is another small bug when updating the `v-model` value, which causes the text color buttons in the toolbar to be rendered incorrectly.

I've filed a bug report for this issue here:
- #6954

**Comment by quantumwebco** [comment]
I still have this issue with the latest quill and primevue 
If I get something from the API and it has a content prop which the editor uses as a model, the editor never loads the content, but as soon as I start typing the editor overwrites the model

**Comment by FeBe95** [comment]
@quantumwebco Could you create a reproducer on stackblitz for this? Make sure to install the exact same package versions that you are using right now.

**Comment by quantumwebco** [comment]
> Hi! I have a question, is this only fixed for primevue 4.2.5? Upgrading quill to 2.0.3 didn't fix the issue - console error disappeared but v-model is still not being updated. On the other hand updating our project from 4.0.0 to 4.2.5 causes it to display countless number of bugs (labels suddenly appear to the right of inputs instead of above them, buttons keep messing with the wrong state etc). Is there maybe some kind of migration guide between each primevue version? TIA

We're on 4.3.3 and quill 2.0.3 and we don't have the bugs you mention, but the editor doesn't load content from v-model

**Comment by FeBe95** [comment]
It seems like they've replaced the original fix in PrimeVue 3.3.0. Take a look at those two commits:
- Original Fix: https://github.com/primefaces/primevue/commit/dbe6d2cae33c45667f891def73f0548b50301750
- Change 1: https://github.com/primefaces/primevue/commit/49c9303c7506ff18511bb38003faaca46a5d9423
- Change 2: https://github.com/primefaces/primevue/commit/615c79dfcef8ad139de25496a77efdb6e1d888f5

I've created a reproducer on stackblitz with PrimeVue 4.3.3 and Quill 2.0.3, and everything seems to work fine.
- The editor's content is updated whenever the model value is changed.
- All toolbar buttons remain intact, no extra labels, no other visual bugs.

You can find the reproducer here:
https://stackblitz.com/edit/primevue-4-vite-issue-template-dbzy5yq3?file=package-lock.json

Please make sure that you are actually using the latest versions, e.g. using this command:
```
npm ls primevue quill
```

If it's still not working for you, please create a reproducer that actually shows the bugs that you are experiencing.

**Comment by nxtkofi** [comment]
I'm sorry, the issue is indeed fixed. 
My mistake was updating primevue and primevue nuxt module to 4.3.3, but forgetting about primevue/themes :') After upgrading themes along with the others everything works perfectly fine.

**Comment by rhaymisonbetini** [comment]
@LeonardoRochaInacio is the best solution for me with  "quill": "^2.0.3",
