### ISSUE TITLE
Tabs: StackBlitz failing to install dependencies

### ISSUE THREAD

**Issue by 23457890** [primefaces/primevue#5732]
### Describe the bug

Error when trying to edit code on StackBlitz.  I noticed this on the "tabs" component page, but this likely impacts all StackBlitz examples.

Error:   Failed to scan for dependencies from entries:
  /home/projects/ay6r74--run/index.html

  ✘ [ERROR] Unterminated string literal

    src/main.js:37:44:
      37 │ import DatePicker from 'primevue/datepicker;
         ╵                                             ^

    at failureErrorWithLog (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1639:15)
    at eval (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1048:25)
    at runOnEndCallbacks (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1474:45)
    at buildResponseToResult (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1046:7)
    at eval (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1058:9)
    at requestCallbacks.on-end (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:719:19)
    at handleIncomingPacket (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/home/projects/ay6r74--run/node_modules/esbuild/lib/main.js:669:7)
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
5:16:44 PM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/projects/ay6r74--run/src/main.js:38:36
  36 |  import DataView from 'primevue/dataview';
  37 |  import DatePicker from 'primevue/datepicker;
  38 |  import DeferredContent from 'primevue/deferredcontent';
     |                                     ^
  39 |  import Dialog from 'primevue/dialog';
  40 |  import DialogService from 'primevue/dialogservice'
      at formatError (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44114:46)
      at TransformContext.error (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44110:19)
      at TransformContext.transform (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41836:22)
      at async Object.transform (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44404:30)
      at async loadAndTransform (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55078:29)
      at async viteTransformMiddleware (/home/projects/ay6r74--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64482:32)

### Reproducer

NA

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vue CLI App

### Steps to reproduce the behavior

1. Try editing "Tabs" code on StackBlitz

**Comment by blevinelrp** [comment]
Invalid JS issue seems to be fixed.
But there are still multiple issues with the "Tabs" examples.

From the console:
> Failed to resolve component: Tab
> Failed to resolve component: TabList
> Failed to resolve component: TabPanels
> Failed to resolve component: Tabs

And as expected, the "Tabs" functionality then does not work.

**Comment by tugcekucukoglu** [comment]
It was fixed. Thank you.

https://v4.primevue.org/tabs/

**Comment by nimonian** [comment]
Unfortunately at least the Tab Menu example still fails to open:

```
Error: The following dependencies are imported but could not be resolved:

  @primevue/themes (imported by /home/projects/j7u9ey--run/src/components/ThemeSwitcher.vue?id=0)
  @primevue/themes/aura (imported by /home/projects/j7u9ey--run/src/components/ThemeSwitcher.vue?id=0)
  @primevue/themes/lara (imported by /home/projects/j7u9ey--run/src/components/ThemeSwitcher.vue?id=0)
  @primevue/themes/nora (imported by /home/projects/j7u9ey--run/src/components/ThemeSwitcher.vue?id=0)

Are they installed?
    at eval (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45831:23)
    at async eval (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45239:38)
Failed to resolve import "@primevue/themes" from "src/presets/Noir.js". Does the file exist?
Failed to resolve import "@primevue/themes" from "src/components/ThemeSwitcher.vue". Does the file exist?
02:20:36 [vite] Internal server error: Failed to resolve import "@primevue/themes" from "src/presets/Noir.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/projects/j7u9ey--run/src/presets/Noir.js:1:31
  1  |  import { definePreset } from '@primevue/themes';
     |                                ^
  2  |          import Aura from '@primevue/themes/aura';
  3  |  
      at formatError (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44114:46)
      at TransformContext.error (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44110:19)
      at normalizeUrl (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41896:33)
      at async eval (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:42050:47)
      at async TransformContext.transform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41966:13)
      at async Object.transform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44404:30)
      at async loadAndTransform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55078:29)
      at async viteTransformMiddleware (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64482:32)
02:20:36 [vite] Internal server error: Failed to resolve import "@primevue/themes" from "src/components/ThemeSwitcher.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/projects/j7u9ey--run/src/components/ThemeSwitcher.vue:68:58
  1  |  
  2  |  import { $t, updatePreset, updateSurfacePalette } from '@primevue/themes';
     |                                                           ^
  3  |  import Aura from '@primevue/themes/aura';
  4  |  import Lara from '@primevue/themes/lara';
      at formatError (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44114:46)
      at TransformContext.error (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44110:19)
      at normalizeUrl (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41896:33)
      at async eval (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:42050:47)
      at async TransformContext.transform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41966:13)
      at async Object.transform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44404:30)
      at async loadAndTransform (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55078:29)
      at async viteTransformMiddleware (file:///home/projects/j7u9ey--run/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64482:32)
 
```
