### ISSUE TITLE
InputText: Name attribute not applied when used outside of Form component

### ISSUE THREAD

**Issue by robm-masabi** [primefaces/primevue#6737]
### Describe the bug

When you use an InputText component _outside_ of a `Form` component - note the capital F here - (e.g. inside a native `<form>` element or otherwise) and you apply a `name` attribute to that InputText component, then the `name` attribute is not rendered in the resulting markup.

This is a regression from previous versions of Primevue, and is not mentioned in any changelog. Therefore, I'm assuming its a bug.

Examples on [the component's documentation](https://primevue.org/inputtext/) feature the component being used outside of the `<Form>` parent (e.g. within a `<div>`), and do not indicate that certain fields will only render within a given context.

Since `name`s are [used for native form submission](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name), the removal of this functionality is, I believe, a breaking change.

### Reproducer

https://stackblitz.com/edit/nlblb9-7eepxq?file=src%2FApp.vue,package.json

### PrimeVue version

4.2.0

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

Add a `name` attribute to an InputText element.

View the resulting HTML rendered.

NB: This also affects other input types too - but InputText is the most widely used and easy to reproduce.

### Expected behavior

The `name` attribute set on the InputText element should appear on the `input` element in the HTML, as described in the documenation.

e.g.
```
<InputText name="some-value" v-model="exampleRef" /> 
```
...should render....
```
<input name="some-value />
```

**Comment by Arsolitt** [comment]
+1 same

**Comment by galaxyblur** [comment]
Seeing this w/ Textarea, too -- presumably all form inputs. This prevents me from using a traditional form redirect action.

**Comment by kedrzu** [comment]
As a workaround you can use pass through: https://primevue.org/passthrough/
```
<InputText pt:root:name="customName" ... />
```

**Comment by Abassion** [comment]
#6890

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primevue/issues/6891

**Comment by gimler** [comment]
pass through for DatePicker
 ```
 <InputText pt:pcInputText:root:name="customName" ... />
 ```

**Comment by AntonLindell** [comment]
+1, this is still not working for me even after https://github.com/primefaces/primevue/issues/6891.

Works with :pt:root:name="name" as said by others.

**Comment by maxkoryukov** [comment]
hey. I'm not sure, if i'm doing everything the expected way, but for me `name="someName"` on a `ToggleSwitch` doesn't work too, so the attribute doesn't appear in the resulting HTML. and one can't "submit" a form with this component.

_but i will review my app first, i don't know if it is a library's bug_

PrimeVue v4.5.4

though, it works with `pt:root:name="name"`.
