### ISSUE TITLE
Gallery: Item navigators are permanently disabled

### ISSUE THREAD

**Issue by ekh-anadeainc** [primefaces/primevue#7321]
### Describe the bug

Item navigators are permanently disabled in the gallery component.

This happens because the GalleriaThumbnails component uses computed properties instead of functions to determine the disabled state, and GalleriaItem still uses functions.

### Pull Request Link

https://github.com/primefaces/primevue/pull/7319

### Reproducer

https://primevue.org/galleria/#itemwithouthumbnails

### Environment

Any environment

### Vue version

3.5.13

### PrimeVue version

4.3.0

### Node version

20

### Steps to reproduce the behavior

1. Open the official documentation website: https://primevue.org/galleria/#itemwithouthumbnails
2. Try to click on the next or previous button

### Expected behavior

Actual behavior: Nothing happens
Expected behavior: The user sees the next/previous image

**Comment by catalinp2004** [comment]
Came across this issue when upgrading to PriveVue 4.3.1. Looking forward to having the fix published.

**Comment by anthonylan** [comment]
The navigators are still disabled

**Comment by ekh-anadeainc** [comment]
> The navigators are still disabled

The fix has not been released yet. Should be fixed in version 4.3.2.

**Comment by DenisLantero** [comment]
I updated to version `4.3.2` but I still have this issue.
I checked both in `node_modules/primevue/package.json` and in `node_modules/@primevue/core/package.json`, both are version 4.3.2.

For reference, this is the code that I have, which is basically the same as the one in the documentation:  

```vue
<template>
  <Galleria
    :value="mediaDocuments"
    :responsive-options="responsiveOptions"
    :num-visible="5"
    container-style="max-width: 640px"
    :prev-button-props="{ disabled: false }"
    :next-button-props="{ disabled: false }"
  >
    <template #item="slotProps">
      <img :src="slotProps.item.url" :alt="slotProps.item.name" style="width: 100%">
    </template>
    <template #thumbnail="slotProps">
      <img :src="slotProps.item.thumbnailUrl" :alt="slotProps.item.name">
    </template>
  </Galleria>
</template>

<script setup lang="ts">
import type { LbTicketAttachmentsGalleryProps } from '@/types'
import type { GalleriaResponsiveOptions } from 'primevue'

const _props = defineProps<LbTicketAttachmentsGalleryProps>()

const responsiveOptions = ref<GalleriaResponsiveOptions[]>([
  {
    breakpoint: '1300px',
    numVisible: 4,
  },
  {
    breakpoint: '575px',
    numVisible: 1,
  },
])
</script>
```

As you can see I even tried to explicitly set `disabled` to false in both buttons, but they remain disabled.

Please let me know if I am doing something wrong, thanks.

**Comment by ekh-anadeainc** [comment]
> [
>   {
>     breakpoint: '1300px',
>     numVisible: 4,
>   },
>   {
>     breakpoint: '575px',
>     numVisible: 1,
>   },
> ]

As I understand it, you are talking about thumbnail buttons, but this issue was about navigation buttons, which are enabled by the `show-item-navigators` property.

**Comment by DenisLantero** [comment]
> > I updated to version 4.3.2 but I still have this issue.
> > I checked both in node_modules/primevue/package.json and in node_modules/@primevue/core/package.json, both are version 4.3.2.
> 
> As I understand it, you are talking about thumbnail buttons, but this issue was about navigation buttons, which are enabled by the `show-item-navigators` property.

Oh my bad, I thought they were the same thing. Is there another open issue about the thumbnails navigation buttons being disabled or should I create one myself?

Also, I tried to change `num-visible` to 1 an indeed the thumbnail buttons weren't disabled anymore and the navigation worked, but I only see the preview of the current image, which defeats the purpose of the thumbnail navigation.

Let me know if I should open another issue for the thumbnail navigation buttons to avoid notifying users subscribed to this thread, thanks.

**Comment by ekh-anadeainc** [comment]
> > > I updated to version 4.3.2 but I still have this issue.
> > > I checked both in node_modules/primevue/package.json and in node_modules/@primevue/core/package.json, both are version 4.3.2.
> > 
> > 
> > As I understand it, you are talking about thumbnail buttons, but this issue was about navigation buttons, which are enabled by the `show-item-navigators` property.
> 
> Oh my bad, I thought they were the same thing. Is there another open issue about the thumbnails navigation buttons being disabled or should I create one myself?
> 
> Also, I tried to change `num-visible` to 1 and indeed the thumbnail buttons weren't disabled anymore and the navigation worked, but I only see the preview of the current image, which defeats the purpose of the thumbnail navigation.
> 
> Let me know if I should open another issue for the thumbnail navigation buttons to avoid notifying users subscribed to this thread, thanks.

If there is no such issue, you can create a new one.
